# SPDX-FileCopyrightText: 2025 Ludwig Hülk <https://github.com/Ludee> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: ENERO Foundry <https://github.com/ENEROFoundry/ENEROFoundry>
# SPDX-License-Identifier: MIT

# Project
site_name: ENERO Foundry
site_url: https://github.com/ENEROFoundry/ENEROFoundry
site_description: Website of the ENERO Foundry

# Repository
repo_name: ENEROFoundry
repo_url: https://github.com/ENEROFoundry/ENEROFoundry
docs_dir: docs
copyright: ENERO Foundry &copy; Reiner Lemoine Institut &copy; Universität Osnabrück &copy; OFFIS Institut für Informatik &copy; Carl von Ossietzky Universität Oldenburg | CC-BY-4.0

# Configuration
theme:
  name: material
  logo: img/OpenEnergyFamily_Logo_ENEROFoundry.png
  favicon: img/Favicon_oeo-foundry.ico
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.follow

# extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: "#"

plugins:
- search:
    separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

# Customization
extra:
  generator: false
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ENEROFoundry/ENEROFoundry

extra_css:
  - extra.css

# Navigation
nav:
  - Home: index.md
  - Community: community.md
  - Principles:
      - Overview: principles.md
      - Openness: principles/1_open.md
      - Common Format: principles/2_format.md
      - Textual Definitions: principles/8_definitions.md
      - Identifier and Naming Conventions: principles/7_naming.md
      - Versioning: principles/5_version.md
      - Foundational Ontology: principles/3_bfo.md
      - Scope: principles/6_scope.md
      - Documentation: principles/9_documentation.md
      - Usage of AI: principles/11_ai_usage.md
      - Collaboration and Responsiveness: principles/10_collaboration.md


  - Ontologies: ontologies.md
  - Contact: contact.md
