# SPDX-FileCopyrightText: 2025 Ludwig Hülk <https://github.com/Ludee> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: OEO Foundry website <https://github.com/OEOFoundry/website>
# SPDX-License-Identifier: MIT

# Project
site_name: OEO Foundry
site_url: https://github.com/OEOFoundry/OEOFoundry
site_description: Website of the OEO Foundry

# Repository
repo_name: OEOFoundry
repo_url: https://github.com/OEOFoundry/OEOFoundry
docs_dir: docs
copyright: OEO Foundry &copy; Reiner Lemoine Institut &copy; Universität Osnabrück &copy; OFFIS Institut für Informatik; &copy; Carl von Ossietzky Universität Oldenburg | CC-BY-4.0

# Configuration
theme:
  name: material
  logo: img/OpenEnergyFamily_Logo_OEOFoundry.png
  favicon: img/favicon_oeo-foundry.ico
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.follow

# extensions
markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true

plugins:
- search:
    separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

# Customization
extra:
  generator: false
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OEOFoundry/OEOFoundry

extra_css:
  - extra.css

# Navigation
nav:
  - Home: index.md
  - Community: community.md
  - Principles:
      - Overview: principles.md
      - 1. Open: principles/1_open.md
      - 2. Common Format: principles/2_format.md
      - 3. Upper Ontology Structure: principles/3_bfo.md
      - 4. Identifier Space: principles/4_id.md
      - 5. Versioning: principles/5_version.md
      - 6. Scope: principles/6_scope.md
      - 7. Naming Conventions: principles/7_naming.md
      - 8. Textual Definitions: principles/8_definitions.md
      - 9. Documentation: principles/9_documentation.md
      - 10. Commitment To Collaboration: principles/10_collaboration.md
  - Ontologies: ontologies.md
  - Contact: contact.md
